#pragma once

#ifndef __EXITCODE_H__
#define __EXITCODE_H__

#define NET_TYPE_ERROR  101
#define GET_RAND_VALUE_ERROR 102
#define GET_RING_WHEN_TOPO 103
#define GET_RAND_SIZE_ERROR 104
#define OPEN_FILE_ERROR_WHEN_APPEND 105
#define OPEN_FILE_ERROE_WHEN_TRUNCATE 106
#define OPEN_FILE_ERROR_WHEN_READ 107
#define SAMPLE_EMPTY 108

#endif // !__EXITCODE_H__